name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3        
      - name: npm install
        run: npm ci  
      - name: Build and push the image
        run: |
            docker login --username Nivedithabp --password ${{secrets.ACCESS_TOKEN}} ghcr.io
            docker build -t ghcr.io/nivedithabp/arithmetic-service:1 --file Dockerfile .
            docker push ghcr.io/nivedithabp/arithmetic-service:1
      - name: Publish the image to azure container registry
        run: |
            docker login --username practicumregistry --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicumregistry.azurecr.io
            docker tag ghcr.io/nivedithabp/arithmetic-service:1 practicumregistry.azurecr.io/arithmetic-service:1
            docker push practicumregistry.azurecr.io/arithmetic-service:1
    